### ISSUE TITLE
TypeError: ViteRestart is not a function

### ISSUE THREAD

**Issue by acalvino4** [antfu/vite-plugin-restart#11] opened 2022-04-27 03:48 UTC
I have a pretty straightforward config, taken basically straight from the docs:

```
import ViteRestart from 'vite-plugin-restart';


export default ({ command }) => ({
  ...
  plugins: [
    ViteRestart({
      restart: [
          './templates/**/*',
      ],
    }),
  ],
  ...
});
```

Yet when I do `npm run build` I get
```
failed to load config
error during build:
TypeError: ViteRestart is not a function
```

Why does this most basic usage fail?

When I replace the first line with
```
import vpr from 'vite-plugin-restart';
let ViteRestart = vpr.default
```
I no longer get that error. Are the docs wrong or is there a bug?

**Comment by acalvino4** [comment] 2022-04-27 03:50
Extended Error:
```
failed to load config from config/build/vite.config.js
error during build:
TypeError: ViteRestart is not a function
    at default (file:config/build/vite.config.js?t=1651031117742:19:5)
    at loadConfigFromFile (node_modules/vite/dist/node/chunks/dep-3397b401.js:61701:15)
    at async resolveConfig (node_modules/vite/dist/node/chunks/dep-3397b401.js:61224:28)
    at async doBuild (node_modules/vite/dist/node/chunks/dep-3397b401.js:41172:20)
    at async build (node_modules/vite/dist/node/chunks/dep-3397b401.js:41160:16)
    at async CAC.<anonymous> (node_modules/vite/dist/node/cli.js:738:9)
```

**Comment by like0413** [comment] 2022-07-26 06:44
same question

**Comment by antfu** [comment] 2022-07-27 06:42
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed as completed by antfu** 2022-07-27 06:42 UTC

**Comment by qodesmith** [comment] 2022-08-06 15:38
@antfu I was able to recreate this quite easily. You can do it in under 3 minutes:

* Create a new React/TS app with `npm create vite@latest`
* Install this library - `npm install vite-plugin-restart`
* Consume ViteRestart in `vite.config.ts` like so:

```TypeScript
import {defineConfig} from 'vite'
import react from '@vitejs/plugin-react'
import ViteRestart from 'vite-plugin-restart'

export default defineConfig({
  plugins: [
    react(),
    ViteRestart({restart: ['tsconfig.node.json']})],
})
```

* Run the app with `npm run dev`
* Boom, you get the error in the console:

```
failed to load config from /Users/qodesmith/repos/vite-plugin-restart-error-example/vite.config.ts
error when starting dev server:
TypeError: ViteRestart is not a function
    at file:///Users/qodesmith/repos/vite-plugin-restart-error-example/vite.config.ts.timestamp-1659798275769.mjs:6:22
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:541:24)
    at async loadConfigFromBundledFile (file:///Users/qodesmith/repos/vite-plugin-restart-error-example/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:62893:21)
    at async loadConfigFromFile (file:///Users/qodesmith/repos/vite-plugin-restart-error-example/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:62780:28)
    at async resolveConfig (file:///Users/qodesmith/repos/vite-plugin-restart-error-example/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:62398:28)
    at async createServer (file:///Users/qodesmith/repos/vite-plugin-restart-error-example/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:59018:20)
    at async CAC.<anonymous> (file:///Users/qodesmith/repos/vite-plugin-restart-error-example/node_modules/vite/dist/node/cli.js:699:24)
```

I'm using Node v18.6.0 on a MacBook pro (2021 with the M1 chip, OS version 12.4)

My current solution is to implement a `try/catch`:
```TypeScript
import {defineConfig} from 'vite'
import react from '@vitejs/plugin-react'
import ViteRestart from 'vite-plugin-restart'

const viteRestartValue = (() => {
  try {
    return ViteRestart({restart: ['tsconfig.node.json']})
  } catch {
    // @ts-ignore - Doesn't look like `vite-plugin-restart` exports correctly.
    return ViteRestart.default({restart: ['tsconfig.node.json']})
  }
})()

export default defineConfig({
  plugins: [react(), viteRestartValue],
})
```

**Comment by acalvino4** [comment] 2022-08-06 17:44
> @antfu I was able to recreate this quite easily. You can do it in under 3 minutes:
> 
> * Create a new React/TS app with `npm create vite@latest`
> * Install this library - `npm install vite-plugin-restart`
> * Consume ViteRestart in `vite.config.ts` like so:
> 
> ```ts
> import {defineConfig} from 'vite'
> import react from '@vitejs/plugin-react'
> import ViteRestart from 'vite-plugin-restart'
> 
> export default defineConfig({
>   plugins: [
>     react(),
>     ViteRestart({restart: ['tsconfig.node.json']})],
> })
> ```
> 
> * Run the app with `npm run dev`
> * Boom, you get the error in the console:
> 
> ```
> failed to load config from /Users/qodesmith/repos/vite-plugin-restart-error-example/vite.config.ts
> error when starting dev server:
> TypeError: ViteRestart is not a function
>     at file:///Users/qodesmith/repos/vite-plugin-restart-error-example/vite.config.ts.timestamp-1659798275769.mjs:6:22
>     at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
>     at async Promise.all (index 0)
>     at async ESMLoader.import (node:internal/modules/esm/loader:541:24)
>     at async loadConfigFromBundledFile (file:///Users/qodesmith/repos/vite-plugin-restart-error-example/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:62893:21)
>     at async loadConfigFromFile (file:///Users/qodesmith/repos/vite-plugin-restart-error-example/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:62780:28)
>     at async resolveConfig (file:///Users/qodesmith/repos/vite-plugin-restart-error-example/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:62398:28)
>     at async createServer (file:///Users/qodesmith/repos/vite-plugin-restart-error-example/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:59018:20)
>     at async CAC.<anonymous> (file:///Users/qodesmith/repos/vite-plugin-restart-error-example/node_modules/vite/dist/node/cli.js:699:24)
> ```
> 
> I'm using Node v18.6.0 on a MacBook pro (2021 with the M1 chip, OS version 12.4)
> 
> My current solution is to implement a `try/catch`:
> 
> ```ts
> import {defineConfig} from 'vite'
> import react from '@vitejs/plugin-react'
> import ViteRestart from 'vite-plugin-restart'
> 
> const viteRestartValue = (() => {
>   try {
>     return ViteRestart({restart: ['tsconfig.node.json']})
>   } catch {
>     // @ts-ignore - Doesn't look like `vite-plugin-restart` exports correctly.
>     return ViteRestart.default({restart: ['tsconfig.node.json']})
>   }
> })()
> 
> export default defineConfig({
>   plugins: [react(), viteRestartValue],
> })
> ```

Agreed. 

@antfu my initial posting has a minimal working example, not sure what other info you need....

**Comment by Teajey** [comment] 2022-08-24 23:58
I'm having the exact same issue with [`vite-plugin-string`](https://github.com/aweikalee/vite-plugin-string), interested to find a proper fix. It's probably a configuration issue, or something upstream.

Edit: It's probably also useful to note that I copied my `vite.config.ts` from another repo where it was working perfectly fine.

**Comment by terranc** [comment] 2022-11-05 03:54
the same question

**Comment by qodesmith** [comment] 2022-11-05 11:27
I wonder if it has to do with the fact that `"type": "module"` is missing from the package.json? @antfu

**Comment by idrm** [comment] 2022-11-05 15:52
Here's a repro of the issue: https://stackblitz.com/edit/vitejs-vite-un3snv

In addition to the already mentioned workaround hack by @qodesmith, it's also possible to "fix" the issue by changing the package type from the original `module` to `commonjs` inside `package.json`.
