### ISSUE TITLE
keeps rebooting

### ISSUE THREAD

**Issue by 1328572844** [antfu/vite-plugin-restart#13] opened 2022-06-10 09:20 UTC
Update the configuration，It keeps rebooting

**Comment by antfu** [comment] 2022-06-10 09:47
We temporarily close this due to the lack of enough information.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Closed as completed by antfu** 2022-06-10 09:47 UTC
